# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'extra_timer.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_extra_timer(object):
    def setupUi(self, extra_timer):
        extra_timer.setObjectName("extra_timer")
        extra_timer.resize(400, 512)
        self.verticalLayout = QtWidgets.QVBoxLayout(extra_timer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(extra_timer)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(extra_timer)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.timer_label = QtWidgets.QLineEdit(extra_timer)
        self.timer_label.setObjectName("timer_label")
        self.horizontalLayout_3.addWidget(self.timer_label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.current_time = QtWidgets.QLabel(extra_timer)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.current_time.setFont(font)
        self.current_time.setAlignment(QtCore.Qt.AlignCenter)
        self.current_time.setObjectName("current_time")
        self.verticalLayout.addWidget(self.current_time)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_timer = QtWidgets.QPushButton(extra_timer)
        self.start_timer.setObjectName("start_timer")
        self.horizontalLayout.addWidget(self.start_timer)
        self.stop_timer = QtWidgets.QPushButton(extra_timer)
        self.stop_timer.setObjectName("stop_timer")
        self.horizontalLayout.addWidget(self.stop_timer)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.set = QtWidgets.QPushButton(extra_timer)
        self.set.setObjectName("set")
        self.verticalLayout_2.addWidget(self.set)
        self.timeEdit = QtWidgets.QTimeEdit(extra_timer)
        self.timeEdit.setCurrentSection(QtWidgets.QDateTimeEdit.MinuteSection)
        self.timeEdit.setObjectName("timeEdit")
        self.verticalLayout_2.addWidget(self.timeEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.forward = QtWidgets.QRadioButton(extra_timer)
        self.forward.setObjectName("forward")
        self.horizontalLayout_2.addWidget(self.forward)
        self.backward = QtWidgets.QRadioButton(extra_timer)
        self.backward.setObjectName("backward")
        self.horizontalLayout_2.addWidget(self.backward)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = QtWidgets.QPushButton(extra_timer)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(extra_timer)
        self.start_timer.clicked.connect(extra_timer.start_timer)
        self.stop_timer.clicked.connect(extra_timer.stop_timer)
        self.set.clicked.connect(extra_timer.set_timer)
        self.forward.clicked.connect(extra_timer.set_forward)
        self.backward.clicked.connect(extra_timer.set_backward)
        self.pushButton.clicked.connect(extra_timer.close_button)
        QtCore.QMetaObject.connectSlotsByName(extra_timer)

    def retranslateUi(self, extra_timer):
        _translate = QtCore.QCoreApplication.translate
        extra_timer.setWindowTitle(_translate("extra_timer", "Dialog"))
        self.label.setText(_translate("extra_timer", "Extra Timer"))
        self.label_2.setText(_translate("extra_timer", "Timer Label:"))
        self.current_time.setText(_translate("extra_timer", "00:00"))
        self.start_timer.setText(_translate("extra_timer", "Start"))
        self.stop_timer.setText(_translate("extra_timer", "Stop"))
        self.set.setText(_translate("extra_timer", "Set"))
        self.timeEdit.setDisplayFormat(_translate("extra_timer", "mm:ss"))
        self.forward.setText(_translate("extra_timer", "Forwards"))
        self.backward.setText(_translate("extra_timer", "Backwards"))
        self.pushButton.setText(_translate("extra_timer", "Close"))

