# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setup.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_settings(object):
    def setupUi(self, settings):
        settings.setObjectName("settings")
        settings.resize(1081, 331)
        self.horizontalLayout = QtWidgets.QHBoxLayout(settings)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.teamLeft = QtWidgets.QLabel(settings)
        self.teamLeft.setObjectName("teamLeft")
        self.horizontalLayout_2.addWidget(self.teamLeft)
        self.teamLeftOptions = QtWidgets.QComboBox(settings)
        self.teamLeftOptions.setObjectName("teamLeftOptions")
        self.horizontalLayout_2.addWidget(self.teamLeftOptions)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.jerseyLeft = QtWidgets.QLabel(settings)
        self.jerseyLeft.setObjectName("jerseyLeft")
        self.horizontalLayout_3.addWidget(self.jerseyLeft)
        self.jerseyLeftOptions = QtWidgets.QComboBox(settings)
        self.jerseyLeftOptions.setObjectName("jerseyLeftOptions")
        self.horizontalLayout_3.addWidget(self.jerseyLeftOptions)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.refreshButton = QtWidgets.QPushButton(settings)
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout_6.addWidget(self.refreshButton)
        self.saveButton = QtWidgets.QPushButton(settings)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_6.addWidget(self.saveButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(settings)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.teamRight = QtWidgets.QLabel(settings)
        self.teamRight.setObjectName("teamRight")
        self.horizontalLayout_4.addWidget(self.teamRight)
        self.teamRightOptions = QtWidgets.QComboBox(settings)
        self.teamRightOptions.setObjectName("teamRightOptions")
        self.horizontalLayout_4.addWidget(self.teamRightOptions)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.jerseyRight = QtWidgets.QLabel(settings)
        self.jerseyRight.setObjectName("jerseyRight")
        self.horizontalLayout_7.addWidget(self.jerseyRight)
        self.jerseyRightOptions = QtWidgets.QComboBox(settings)
        self.jerseyRightOptions.setObjectName("jerseyRightOptions")
        self.horizontalLayout_7.addWidget(self.jerseyRightOptions)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton = QtWidgets.QPushButton(settings)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.closeButton = QtWidgets.QPushButton(settings)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_5.addWidget(self.closeButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(settings)
        self.closeButton.clicked.connect(settings.close)
        self.saveButton.clicked.connect(settings.save)
        self.refreshButton.clicked.connect(settings.refresh)
        self.pushButton.clicked.connect(settings.swap)
        self.jerseyRightOptions.activated['QString'].connect(settings.highlighted_right)
        self.jerseyLeftOptions.activated['QString'].connect(settings.highlighted_left)
        QtCore.QMetaObject.connectSlotsByName(settings)

    def retranslateUi(self, settings):
        _translate = QtCore.QCoreApplication.translate
        settings.setWindowTitle(_translate("settings", "Settings"))
        self.teamLeft.setText(_translate("settings", "Team Left"))
        self.jerseyLeft.setText(_translate("settings", "Jersey Color Left"))
        self.refreshButton.setText(_translate("settings", "Refresh"))
        self.saveButton.setText(_translate("settings", "Save"))
        self.teamRight.setText(_translate("settings", "Team Right"))
        self.jerseyRight.setText(_translate("settings", "Jersey Color Right"))
        self.pushButton.setText(_translate("settings", "Swap Teams"))
        self.closeButton.setText(_translate("settings", "Close"))

